blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('contacts/', include('mailing.urls', namespace='contacts')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import MailingListView, contacts, ClientListView, MailingDetailView, ClientDetailView, \
    LogsListView, MailingDeleteView, MailingCreateView, ClientCreateView, MailingUpdateView, off, ClientDeleteView, \
    ClientUpdateView, HomePageView

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_confirm_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_confirm_delete'),
    path('mailing_detail/off/<int:pk>/', off, name='off'),

    path('contacts/', contacts, name='contacts'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_confirm_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_confirm_delete'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),

    path('logs_list/', LogsListView.as_view(), name='logs_list'),
]

mailing/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='контактный email')
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    comment = models.CharField(max_length=300, verbose_name='комментарий')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец', **NULLABLE)

    def __str__(self):
        return f'{self.email}'

    class Meta:
        verbose_name = 'Клиент сервиса'
        verbose_name_plural = 'Клиенты сервиса'


class Mailing(models.Model):
    PERIOD_CHOICES = [
        ('daily', 'Ежедневная'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    ]

    STATUS_CHOICES = [
        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('done', 'Завершена')

    ]

    start_time = models.DateField(**NULLABLE, verbose_name='начало рассылки')
    end_time = models.DateField(**NULLABLE, verbose_name='конец рассылки')
    period = models.CharField(max_length=20, choices=PERIOD_CHOICES, **NULLABLE, verbose_name='периодичность')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, verbose_name='статус рассылки')
    client = models.ManyToManyField(Client, verbose_name='клиент')
    title_message = models.CharField(max_length=100, verbose_name='тема письма')
    body_message = models.TextField(verbose_name='тело письма', **NULLABLE)

    last_run = models.DateField(verbose_name='дата последней отправки рассылки', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='владелец', **NULLABLE)

    def __str__(self):
        return f'{self.start_time} - {self.end_time} ({self.status} {self.client})'

    class Meta:
        verbose_name = 'Рассылка (настройки)'
        verbose_name_plural = 'Рассылки (настройки)'

    permissions = [
        (
            'deactivate_mailing',
            'Can deactivate settings'
        )
    ]


class Logs(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )
    datetime_of_last_attempt = models.DateTimeField(verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=20, choices=STATUSES, verbose_name='статус попытки')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, **NULLABLE, verbose_name='рассылка')
    error_msg = models.TextField(**NULLABLE, verbose_name='error msg')

    def __str__(self):
        return f'{self.datetime_of_last_attempt} {self.status}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылки'

mailing/forms.py
from django import forms
from mailing.models import Mailing, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('start_time', 'end_time', 'period', 'status', 'client', 'title_message', 'body_message')

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['client'].queryset = Client.objects.filter(owner=user)


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        exclude = ['owner']

mailing/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView, TemplateView

from blog.models import Blog
from mailing.forms import MailingForm, ClientForm
from mailing.models import Client, Mailing, Logs
from mailing.services import time_task


class ChecksUser:
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_superuser:
            raise Http404
        return self.object


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        if form.is_valid:
            new_client = form.save()
            new_client.owner = self.request.user
            new_client.save()

        return super().form_valid(form)


class ClientListView(ChecksUser, ListView):
    model = Client
    template_name = 'mailing/client_list.html'

    def get_queryset(self):
        client = super().get_queryset()
        return client.filter(owner=self.request.user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = 'mailing/client_detail.html'

    def test_func(self):
        objects = self.get_object()
        return self.request.user == objects.owner or self.request.user.is_superuser


class ClientDeleteView(LoginRequiredMixin, ChecksUser, DeleteView):
    model = Client
    template_name = 'mailing/client_confirm_delete.html'
    success_url = reverse_lazy('mailing:client_list')


class ClientUpdateView(LoginRequiredMixin, ChecksUser, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def form_valid(self, form):
        if form.is_valid():
            new_client = form.save()
            new_client.owner = self.request.user
            new_client.save()
        return super().form_valid(form)

    def get_queryset(self):
        return time_task()

    def get_form_kwargs(self):
        user_request = super().get_form_kwargs()
        user_request['user'] = self.request.user
        return user_request


class MailingListView(ListView):
    model = Mailing
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self):
        if self.request.user.has_perm('mailing.deactivate_mailing') or self.request.user.is_superuser:
            mailing = super().get_queryset()
            return mailing
        else:
            mailing = super().get_queryset()
            return mailing.filter(owner=self.request.user)


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'mailing/mailing_detail.html'


class MailingDeleteView(LoginRequiredMixin, ChecksUser, DeleteView):
    model = Mailing
    template_name = 'mailing/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')


class MailingUpdateView(LoginRequiredMixin, ChecksUser, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        user_request = super().get_form_kwargs()
        user_request['user'] = self.request.user
        return user_request


class LogsListView(ListView):
    model = Logs
    template_name = 'mailing/mailing_report.html'


def contacts(request):
    return render(request, 'mailing/contacts.html')


class HomePageView(TemplateView):
    template_name = 'mailing/home.html'

    def get_context_data(self, **kwargs):
        blog = Blog.objects.all()[:3]
        clients_count = len(Client.objects.all())
        mailing_count = len(Mailing.objects.all())
        mailing_active = len(Mailing.objects.filter(status='started'))
        context = super().get_context_data()
        context['mailing_count'] = mailing_count
        context['mailing_active'] = mailing_active
        context['clients_count'] = clients_count
        context['blogs'] = blog

        return context


@permission_required('mailing.deactivate_mailing')
def off(request, pk):
    """Контролер для отключения рассылок"""

    obj = Mailing.objects.get(pk=pk)

    if obj.status == 'created' or 'started':
        obj.status = 'done'
        obj.save()

    return redirect(reverse('mailing:mailing_list'))

mailing/templates/mailing/base.html
<!doctype html>
{% load static %}
  <html lang="ru" data-bs-theme="auto">
    <head><script src="{% static 'js/color-modes.js'%}"></script>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="">
      <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
      <meta name="generator" content="Hugo 0.118.2">
      <title>Рассылка.ру</title>

  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

      <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
      </style>


      <!-- Custom styles for this template -->
      <link href="pricing.css" rel="stylesheet">
    </head>

    <body>

      <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check" viewBox="0 0 16 16">
          <title>Check</title>
          <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
        </symbol>
      </svg>

      <div class="container py-3">
        <header>
          {% include 'mailing/includes/inc_mailing_menu.html' %}
        </header>

        <main>
          <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            {% block content %}
            {% endblock %}
            {% block home %}
            {% endblock %}
          </div>
        </main>

          <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
              <div class="col-12 col-md">
                <small class="d-block mb-3 text-body-secondary">&copy; 2017–2023</small>
              </div>
              <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                  <li class="mb-1"><a class="link-secondary text-decoration-none" href="{% url 'mailing:contacts' %}">Контакты</a></li>
                </ul>
              </div>
            </div>
          </footer>
      </div>
      <script src="{% static 'js/bootstrap.bundle.min.js'%}" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
  </html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p>Удалить клиента?</p>
                            <button type="submit" class="w-100 btn btn-sm btn-outline-danger">Подтвердить</button>
                            <a href="{% url 'mailing:client_list' %}" class="w-100 btn btn-sm btn-outline-success">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Информация по клиенту</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li>ФИО: {{object.full_name}}</li>
              <li>Контактный email: {{object.email}}</li>
              <li>Комментарий: {{object.comment}}</li>
              <li>Владелец: {{object.owner}}</li>
            </ul>
            <a href="{% url 'mailing:client_list' %}" class="w-100 btn btn-sm btn-outline-danger">Назад</a>
          </div>
        </div>
      </div>
{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <h2>Создание клиента</h2>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="w-100 btn btn-sm btn-outline-success">Сохранить</button>
                            <a href="{% url 'mailing:client_list' %}" class="w-100 btn btn-sm btn-outline-danger">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}

  {% for object in object_list%}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Клиент №  {{object.id}}</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li>ФИО: {{object.full_name}}</li>
              <li>Контактный email: {{object.email}}</li>
            </ul>
            <a type="button" class="w-100 btn btn-sm btn-outline-success" href="{% url 'mailing:client_detail' object.pk%}">Подробнее</a>
            <a type="button" class="w-100 btn btn-sm btn-outline-warning" href="{% url 'mailing:client_update' object.pk%}">Редактировать</a>
            <a type="button" class="w-100 btn btn-sm btn-outline-danger" href="{% url 'mailing:client_confirm_delete' object.pk%}">Удалить</a>
          </div>
        </div>
      </div>
  {% endfor%}
{% endblock %}

mailing/templates/mailing/contacts.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="display-4">Контакты</h1>
        <div class="row text-start">
            <div class="col-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <table class="table table-striped">
                            <tr>
                                <td class="w-25">Страна</td>
                                <td>Россия</td>
                            </tr>
                            <tr>
                                <td class="w-25">ИНН</td>
                                <td>9999999999</td>
                            </tr>
                            <tr>
                                <td class="w-25">Адрес</td>
                                <td>Москва, Дворцовая, 19</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="card mb-6 box-shadow">
                    <div class="card-header">
                        <h4 class="my font-weight-normal">Свяжитесь с нами</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" action="" class="form-floating">
                            {% csrf_token %}
                            <div class="mb-8">
                                <label for="name">Имя</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                            </div>
                            <div class="mb-8">
                                <label for="phone">Телефон</label>
                                <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                            </div>
                            <div class="mb-8">
                                <label for="message">Сообщение</label>
                                <textarea type="text" name="message" class="form-control" id="message" placeholder="Доброго времени суток, " required></textarea>
                            </div>
                        </form>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/home.html
{% extends 'mailing/base.html' %}

{% block home %}
<div class="container">
  <div class="row">
    <div class="col-10">
      <p>Всего рассылок: {{mailing_count}}
        из них активных: {{mailing_active}}
        Активных клиентов: {{clients_count}}</p>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-12">
      <h2 class="display-6 text-center mb-4">Возможности</h2>

        <div class="table-responsive">
          <table class="table text-center">
            <thead>
              <tr>
                <th style="width: 34%;"></th>
                <th style="width: 22%;">Бесплатно</th>
                <th style="width: 22%;">Премиум</th>
                <th style="width: 22%;">Всё</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" class="text-start">Создание рассылок</th>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
              </tr>
              <tr>
                <th scope="row" class="text-start">Анонимность</th>
                <td></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
              </tr>
            </tbody>

            <tbody>
              <tr>
                <th scope="row" class="text-start">Отправка рассылок</th>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
              </tr>
              <tr>
                <th scope="row" class="text-start">Контроль рассылок</th>
                <td></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
              </tr>
              <tr>
                <th scope="row" class="text-start">Удаление рассылок</th>
                <td></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
              </tr>
              <tr>
                <th scope="row" class="text-start">Отчет по рассылкам</th>
                <td></td>
                <td></td>
                <td><svg class="bi" width="24" height="24"><use xlink:href="#check"/></svg></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
  </div>
  <div class="row text-center">
    <div class="col-12">
      {% for blog in blogs %}
        <div class="card">
            <div class="card-body">
                <h2>{{blog.title}}
                </h2>
                <p>{{blog.body}} </p>
            </div>
        </div>
      {% endfor%}
    </div>
  </div>
</div>
{% endblock%}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p>Удалить рассылку?</p>
                            <button type="submit" class="w-100 btn btn-sm btn-outline-danger">Подтвердить</button>
                            <a href="{% url 'mailing:mailing_list' %}" class="w-100 btn btn-sm btn-outline-success">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
          <div class="card-header py-3">
            <h4 class="my-0 fw-normal">Рассылка №  {{object.id}}</h4>
          </div>
          <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4">
              <li>Начало: {{object.start_time}}</li>
              <li>Конец: {{object.end_time}}</li>
              <li>Периодичность: {{object.period}}</li>
              <li>Статус: {{object.status}}</li>
              <li>Клиент: {{object.client}}</li>
            </ul>
            <a href="{% url 'mailing:off' object.pk%}" class="w-100 btn btn-sm btn-outline-danger">Отключить рассылку</a>
            <a href="{% url 'mailing:mailing_list'%}" class="w-100 btn btn-sm btn-outline-secondary">Назад</a>
          </div>
        </div>
      </div>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Создание рассылки</h2>
                        <div class="col-12">
                            <div class="card">
                                <div class="card-body">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        <button type="submit" class="w-100 btn btn-sm btn-outline-success">Сохранить</button>
                                        <a href="{% url 'mailing:mailing_list' %}" class="w-100 btn btn-sm btn-outline-danger">Назад</a>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
  {% for object in object_list%}
      <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h4 class="my-0 fw-normal">Рассылка №  {{object.id}}</h4>
            </div>
            <div class="card-body">
              <ul class="list-unstyled mt-3 mb-4">
                <li>{{object.start_time}} - {{object.end_time}}</li>
                <li>----------------------------</li>
                <li>Периодичность: {{object.period}}</li>
              </ul>
              {% if user.is_authenticated %}
                <button type="button" class="w-100 btn btn-sm btn-outline-success">Запустить рассылку</button>
                <a href="{% url 'mailing:off' object.pk%}" class="w-100 btn btn-sm btn-outline-warning">Остановить рассылку</a>
                <a href="{% url 'mailing:mailing_detail' object.pk%}" class="w-100 btn btn-sm btn-outline-info">Просмотр рассылки</a>
                <a href="{% url 'mailing:mailing_update' object.pk%}" class="w-100 btn btn-sm btn-outline-primary">Редактировать рассылку</a>
                <a href="{% url 'mailing:mailing_confirm_delete' object.pk%}" class="w-100 btn btn-sm btn-outline-danger">Удалить рассылку</a>
              {% else %}
                <a href="{% url 'mailing:mailing_detail' object.pk%}" class="w-100 btn btn-sm btn-outline-info">Просмотр рассылки</a>
              {% endif %}
            </div>
          </div>
        </div>
  {% endfor%}
{% endblock %}

mailing/templates/mailing/mailing_report.html
{% extends 'mailing/base.html' %}

{% block content %}
<title>Статистика рассылок</title>
<body>
    <div class="container">
        <h1>Отчет по рассылкам</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Рассылка</th>
                    <th>Дата и время попытки</th>
                    <th>Статус попытки</th>
                    <th>Ответ сервера</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.mailing }}</td>
                        <td>{{ object.datetime_of_last_attempt }}</td>
                        <td>{{ object.status }}</td>
                        <td>{{ object.error_msg }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">Нет данных для отображения.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}