blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('contacts/', include('mailing.urls', namespace='contacts')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from mailing.models import NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержимое статьи')
    image = models.ImageField(upload_to='image/', verbose_name='изображение', **NULLABLE)
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')
    date_published = models.DateTimeField(verbose_name='дата публикации', **NULLABLE)
    
    def __str__(self):
        return f'{self.title} {self.views_count} {self.date_published}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ('title', 'date_published',)

blog/forms.py
from django import forms

from blog.models import Blog
from mailing.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body', 'image',)

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from blog.forms import BlogForm
from blog.models import Blog
from mailing.services import cache_blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return cache_blog()


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')


class BlogUpdateView(UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p>Удалить пост '{{object.title}}' ?</p>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>
                            <a href="{% url 'blog:blog_list' %}" class="p-2 btn btn-outline-primary">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-3 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <ul class="list-unstyled ">
                        <img src="{{ object.image }}" style="width: 80%;"/>
                        <li> ____________________________ </li>
                        <li> {{object.body}} </li>
                        <li> ____________________________ </li>
                        <li> Просмотры: {{ object.views_count }} </li>
                    </ul>
                    <a href="{% url 'blog:blog_list' %}" class="p-2 btn btn-outline-primary">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                                {% if object %}
                                    Сохранить
                                {% else %}
                                    Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}

{% block content %}

<div class="container">
    <div class="col-12 mb-5">
        <a class="w-100 btn btn-sm btn-outline-success" href="{% url 'blog:blog_create' %}">Добавить пост</a>
    </div>
    <div class="row text-center">
            {% for object in object_list %}
                <div class="col-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body" style="width: 90%;">
                            <p class="card-text">{{ object.title }}</p>
                            <p class="card-text">{{ object.body|truncatechars:70 }}</p>
                            <div class="d-flex justify-content-between align-item-center">
                                <div class="btn-group">
                                    <a href="{% url 'blog:blog_view' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">View</a>
                                    <a href="{% url 'blog:blog_update' object.pk %}"
                                       class="btn btn-sm btn-outline-secondary">Edit</a>
                                    <a href="{% url 'blog:blog_delete' object.pk %}"
                                       class="btn btn-sm btn-outline-danger">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
</div>
{% endblock %}