blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogDeleteView, BlogUpdateView

app_name = BlogConfig.name

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='blog_view'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('contacts/', include('mailing.urls', namespace='contacts')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import MailingListView, contacts, ClientListView, MailingDetailView, ClientDetailView, \
    LogsListView, MailingDeleteView, MailingCreateView, ClientCreateView, MailingUpdateView, off, ClientDeleteView, \
    ClientUpdateView, HomePageView

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('mailing_list/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_confirm_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_confirm_delete'),
    path('mailing_detail/off/<int:pk>/', off, name='off'),

    path('contacts/', contacts, name='contacts'),

    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_confirm_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_confirm_delete'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),

    path('logs_list/', LogsListView.as_view(), name='logs_list'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerificationTemplateView, generate_new_password, \
    ErrorVerificationTemplateView, ProfileDeleteView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/confirm_delete/<int:pk>/', ProfileDeleteView.as_view(), name='profile_confirm_delete'),

    path('verify_email/', VerificationTemplateView.as_view(), name='verify_email'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('verify_email/error/', ErrorVerificationTemplateView.as_view(), name='verify_email_error'),
]

users/models.py
import random

from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}

code = ''.join([str(random.randint(0, 9)) for _ in range(12)])


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Почта')
    avatar = models.ImageField(upload_to='user/', verbose_name='Аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    country = models.CharField(max_length=35, verbose_name='Страна', **NULLABLE)
    is_active = models.BooleanField(default=False, verbose_name='Активность')
    email_verified = models.BooleanField(default=False, verbose_name='Верификация почты')

    ver_code = models.CharField(max_length=15, default=code, verbose_name='Проверочный код')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f' {self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)


class UserProfileForm(StyleFormMixin, UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView, DeleteView

from users.forms import UserRegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:verify_email')

    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            send_mail(
                subject='Подтверждение почты',
                message=f'Код {new_user.ver_code}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[new_user.email]
            )
        return super().form_valid(form)


class VerificationTemplateView(TemplateView):
    template_name = 'users/verify_email.html'

    def post(self, request):
        ver_code = request.POST.get('ver_code')
        user_code = User.objects.filter(ver_code=ver_code).first()

        if user_code is not None and user_code.ver_code == ver_code:
            user_code.is_active = True
            user_code.save()
            return redirect('users:login')
        else:
            return redirect('users:verify_email_error')



class ErrorVerificationTemplateView(TemplateView):
    template_name = 'users/verify_email_error.html'
    success_url = reverse_lazy('users:verify_email_error')


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('mailing:home')

    def get_object(self, queryset=None):
        return self.request.user


class ProfileDeleteView(DeleteView):
    model = User
    template_name = 'users/profile_confirm_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(12)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )
    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-12"></div>
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Вход
                </h4>
              </div>
              <div class="card-body">
                  {%csrf_token%}
                  {{form.as_p}}
                  <button type="submit" class="btn btn-success" >Войти</button>
              </div>
              <div class="card-footer"></div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/profile_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <p>Удалить профиль?</p>
                            <button type="submit" class="w-100 btn btn-sm btn-outline-danger">Подтвердить</button>
                            <a href="{% url 'mailing:home' %}" class="w-100 btn btn-sm btn-outline-success">Назад</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-12"></div>
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Регистрация
                </h4>
              </div>
              <div class="card-body">
                  {%csrf_token%}
                  {{form.as_p}}
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success">Регистрация</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-12"></div>
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Профиль
                </h4>
              </div>
              <div class="card-body">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <a class="w-100 btn btn-sm btn-outline-primary" href="{% url 'users:generate_new_password' %}" >Восстановить пароль</a>
                  <a class="w-100 btn btn-sm btn-outline-danger" href="{% url 'users:profile_confirm_delete' object.pk%}" >Удалить профиль</a>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success" >Сохранить</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/verify_email.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-12"></div>
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Введите код
                </h4>
              </div>
              <div class="card-body">
                  {% csrf_token %}

                  <input type="text" name="ver_code" class="form-control" id="ver_code" required>
              </div>
              <div class="card-footer">
                  <button type="submit" class="btn btn-success">Подтвердить</button>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}

users/templates/users/verify_email_error.html
{% extends 'mailing/base.html' %}

{% block content %}
  <div class="col-12">
      <form class='row' method="post" enctype="multipart/form-data">
          <div class="col-4"></div>
          <div class="col-4">
            <div class="card">
              <div class="card-header">
                <h4 class="card-title">
                  Неверный код
                </h4>
              </div>
              <div class="card-body">
              </div>
              <div class="card-footer">
                  <a href="{% url 'users:verify_email' %}" class="btn btn-success">Повторить попытку</a>
              </div>
            </div>
          </div>
      </form>
  </div>
{% endblock %}